---
# tasks file for vmware-vm-shutdown
- name: Stop VMs
  vmware_guest_powerstate:
    hostname: "{{ vsphere.hostname }}"
    username: "{{ vsphere.username }}"
    password: "{{ vsphere.password }}"
    validate_certs: no
    folder: "{{ vsphere.folder }}"
    name: "{{ item }}"
    state: shutdown-guest
  delegate_to: localhost
  register: vmware_vm_shutdown
  with_items: "{{ vm_list.split(',') | list }}"
