---
# tasks file for vmware-vm-start
- name: Start VMs
  vmware_guest_powerstate:
    hostname: "{{ vsphere.hostname }}"
    username: "{{ vsphere.username }}"
    password: "{{ vsphere.password }}"
    validate_certs: no
    folder: "{{ vsphere.folder }}"
    name: "{{ item }}"
    state: powered-on
  delegate_to: localhost
  register: vmware_vm_start
  with_items: "{{ vm_list.split(',') | list }}"
