---
# tasks file for vmware-get-dc
- name: Gather information about all datacenters
  community.vmware.vmware_datacenter_info:
    hostname: "{{ vsphere.hostname }}"
    username: "{{ vsphere.username }}"
    password: "{{ vsphere.password }}"
    validate_certs: no
  delegate_to: localhost
  register: vmware_dc_data
- set_fact:
    vmware_datacenters: "{{ vmware_datacenters | default ([]) + [ item.name ] }}"
  loop: "{{ vmware_dc_data.datacenter_info | list }}"
- debug:
    var: vmware_datacenters
