---
# tasks file for vmware-get-cluster
- name: Gather information about all cluster for a datacenter
  community.vmware.vmware_cluster_info:
    hostname: "{{ vsphere.hostname }}"
    username: "{{ vsphere.username }}"
    password: "{{ vsphere.password }}"
    validate_certs: no
    datacenter: "{{ vsphere.datacenter }}"
  delegate_to: localhost
  register: vmware_cluster_data
- set_fact:
    vmware_clusters: "{{ vmware_clusters | default ([]) + [ item.key ] }}"
  loop: "{{ vmware_cluster_data.clusters | dict2items }}"
- debug:
    var: vmware_clusters
